### ISSUE TITLE
Odysseyn1x requires SecureBoot to be off

### ISSUE THREAD

**Issue by neheb** [cfw-guide/ios.cfw.guide#67]
Recently a user on the jailbreak discord server wrecked his Windows installation by turning SecureBoot off. Device was a Windows Surface 2 with BitLocker enabled stock and no backup key. And no, turning SecureBoot back on did not fix the issue.

Should a section mentioning this issue be placed on the guide? There's an untested solution in the form of https://www.ventoy.net/en/doc_secure.html . No idea if it should be recommended.

**Comment by hopolapopola** [comment]
Correct me if I'm wrong, but when you say `BitLocker enabled stock` do you mean full encryption with a key and all, or the weird half-enabled state that isn't technically active but is pre-configured on some machines to just require setting a key? Because if it's the latter, this is pretty much an issue on every Surface and a lot of other Windows laptops and definitely should be mentioned in the guide

**Comment by xstecky** [comment]
They actually had a Surface Book 2, not a Surface 2 (which is ARM).

**Comment by neheb** [comment]
@hopolapopola well, device has a TPM so no real user key. It was backed up nowhere either. User doesn't have enough knowledge on how to reinstall meaning it's basically a brick right now.

**Comment by hopolapopola** [comment]
@neheb well that's a big ol' yikes
